#!/bin/bash
# Script to help install Claude Code in containers

echo "=== Claude Code Installation Helper ==="
echo ""
echo "Since Claude Code requires authentication and installation,"
echo "you'll need to install it in each container manually."
echo ""
echo "Steps for each container:"
echo ""
echo "1. Enter the container:"
echo "   docker exec -it claude-frontend bash"
echo ""
echo "2. Install Node.js if needed:"
echo "   curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -"
echo "   sudo apt-get install -y nodejs"
echo ""
echo "3. Install Claude Code:"
echo "   npm install -g @anthropic-ai/claude-code"
echo "   OR"
echo "   Follow instructions at: https://claude.ai/code"
echo ""
echo "4. Authenticate Claude:"
echo "   export ANTHROPIC_API_KEY='your-key'"
echo "   claude auth"
echo ""
echo "5. Test it works:"
echo "   claude -p 'Hello, what files are in this directory?'"
echo ""
echo "Repeat for claude-backend and claude-devops containers."